### ISSUE TITLE
[BE] REST docs 적용하기

### ISSUE THREAD

**Issue by ninaaano** [codesquad-members-2023-group5/issue-tracker#50]
## 💡 Issue
API 문서 자동화
https://tecoble.techcourse.co.kr/post/2020-08-18-spring-rest-docs/

## 📝 Todo
- [ ] build.gradle 설정
- [ ] 프로덕션 코드 작성
- [ ] 테스트 코드 작성
- [ ] 문서화
